* org-protocol-github-lines

  The purpose of this plugin is to make it easier to switch from your
  browser to emacs when looking at code reviews
  [[file:http://puntoblogspot.blogspot.com.es/2012/10/github-emacs-org-protocol-github-lines.html][blogpost and demo]]

** Requirements
   org-mode
   org-protocol

** Manual and usage
   In github pull request views, add an emacs button that makes emacs open that file/line.
   [[file:http://puntoblogspot.blogspot.com.es/2012/10/github-emacs-org-protocol-github-lines.html][blogpost and demo]]

   Recently it got support for bitbucket repos also. No interface in
   firefox/chrome yet. To use it in conkeror, `m-x clone-repo` to
   clone (both bb or gh)

** Code
*** Browser
    In browser/org-protocol-github-lines.user.js theres the plugin
    that will insert the links on code comments that will link to
    emacs.

*** OS
    os/xdg-open Predefine org-protocol to open emacsclient

*** Emacs
    org-protocol-github-lines.el contains the code to open the actual file

** Conkeror
	 The js file for conkeror provides a command `m-x clone-repo` which
	 sends the signal to the emacs server to clone the
	 "repo-at-buffer". It works with both github and bitbucket.

* Authors & contribs

  - [[http://github.com/kidd][Raimon Grau Cusco]] <raimonster@gmail.com>
  - [[https://github.com/ruediger][Rüdiger Sonderfeld]] <ruediger@c-plusplus.de>
